//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payamresanusing_cursor.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.wsRayanehSoap")]
    public interface wsRayanehSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewProject(string strParameterFromRayaneh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewProject", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateNewProjectAsync(string strParameterFromRayaneh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pause", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Pause(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pause", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PauseAsync(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Resume(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resume", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResumeAsync(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Break", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Break(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Break", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BreakAsync(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowAllMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ShowAllMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllRunningProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ShowAllRunningProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllRunningProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAllRunningProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllCallerIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ShowAllCallerIds(string strcallerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllCallerIds", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAllCallerIdsAsync(string strcallerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllmessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ShowAllmessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllmessages", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAllmessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllCompletedProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ShowAllCompletedProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllCompletedProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAllCompletedProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RequestOptions(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOptions", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RequestOptionsAsync(string strProjectsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangeOptions(string strNewParameterAndPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOptions", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChangeOptionsAsync(string strNewParameterAndPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Checkuserpass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Checkuserpass(string struser, string strpass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Checkuserpass", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckuserpassAsync(string struser, string strpass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsRayanehSoapChannel : payamresanusing_cursor.ServiceReference1.wsRayanehSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsRayanehSoapClient : System.ServiceModel.ClientBase<payamresanusing_cursor.ServiceReference1.wsRayanehSoap>, payamresanusing_cursor.ServiceReference1.wsRayanehSoap {
        
        public wsRayanehSoapClient() {
        }
        
        public wsRayanehSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsRayanehSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRayanehSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRayanehSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateNewProject(string strParameterFromRayaneh) {
            return base.Channel.CreateNewProject(strParameterFromRayaneh);
        }
        
        public System.Threading.Tasks.Task<string> CreateNewProjectAsync(string strParameterFromRayaneh) {
            return base.Channel.CreateNewProjectAsync(strParameterFromRayaneh);
        }
        
        public string Pause(string strProjectsId) {
            return base.Channel.Pause(strProjectsId);
        }
        
        public System.Threading.Tasks.Task<string> PauseAsync(string strProjectsId) {
            return base.Channel.PauseAsync(strProjectsId);
        }
        
        public string Resume(string strProjectsId) {
            return base.Channel.Resume(strProjectsId);
        }
        
        public System.Threading.Tasks.Task<string> ResumeAsync(string strProjectsId) {
            return base.Channel.ResumeAsync(strProjectsId);
        }
        
        public string Break(string strProjectsId) {
            return base.Channel.Break(strProjectsId);
        }
        
        public System.Threading.Tasks.Task<string> BreakAsync(string strProjectsId) {
            return base.Channel.BreakAsync(strProjectsId);
        }
        
        public string ShowAllMessage() {
            return base.Channel.ShowAllMessage();
        }
        
        public System.Threading.Tasks.Task<string> ShowAllMessageAsync() {
            return base.Channel.ShowAllMessageAsync();
        }
        
        public System.Data.DataSet ShowAllRunningProjects() {
            return base.Channel.ShowAllRunningProjects();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAllRunningProjectsAsync() {
            return base.Channel.ShowAllRunningProjectsAsync();
        }
        
        public System.Data.DataSet ShowAllCallerIds(string strcallerid) {
            return base.Channel.ShowAllCallerIds(strcallerid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAllCallerIdsAsync(string strcallerid) {
            return base.Channel.ShowAllCallerIdsAsync(strcallerid);
        }
        
        public System.Data.DataSet ShowAllmessages() {
            return base.Channel.ShowAllmessages();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAllmessagesAsync() {
            return base.Channel.ShowAllmessagesAsync();
        }
        
        public System.Data.DataSet ShowAllCompletedProjects() {
            return base.Channel.ShowAllCompletedProjects();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAllCompletedProjectsAsync() {
            return base.Channel.ShowAllCompletedProjectsAsync();
        }
        
        public string RequestOptions(string strProjectsId) {
            return base.Channel.RequestOptions(strProjectsId);
        }
        
        public System.Threading.Tasks.Task<string> RequestOptionsAsync(string strProjectsId) {
            return base.Channel.RequestOptionsAsync(strProjectsId);
        }
        
        public string ChangeOptions(string strNewParameterAndPrjId) {
            return base.Channel.ChangeOptions(strNewParameterAndPrjId);
        }
        
        public System.Threading.Tasks.Task<string> ChangeOptionsAsync(string strNewParameterAndPrjId) {
            return base.Channel.ChangeOptionsAsync(strNewParameterAndPrjId);
        }
        
        public bool Checkuserpass(string struser, string strpass) {
            return base.Channel.Checkuserpass(struser, strpass);
        }
        
        public System.Threading.Tasks.Task<bool> CheckuserpassAsync(string struser, string strpass) {
            return base.Channel.CheckuserpassAsync(struser, strpass);
        }
    }
}
